apiVersion: v1
kind: Service
metadata:
  name: react-app
  namespace: default
spec:
  selector:
    app: react-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8083
      nodePort: 8083
  type: LoadBalancer
