apiVersion: v1
kind: Service
metadata:
  name: react-app
  namespace: default
spec:
  selector:
    app: react-app
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085
  type: LoadBalancer
